# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-swift-pjsua2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift'
  pod 'NKVPhonePicker'
  pod 'NexmoClient'
  pod 'CountryPickerView'
  pod 'KNContacts'
  pod 'KDCircularProgress'
  pod 'GradientProgress'
  pod "PagingKit"
  pod 'Alamofire'
  pod 'SwiftySound'
  pod 'ProgressHUD'
  pod 'lottie-ios'
  pod 'OpenTok'
  pod 'Socket.IO-Client-Swift'
  pod 'InputBarAccessoryView'
  pod 'RealmSwift'
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'FirebaseAnalytics'
  pod 'MessageKit'
  pod 'Firebase/Crashlytics'
  pod 'Alamofire'
  pod 'GraphQLite'
  pod 'SDWebImage'
  pod 'ImageViewer.swift'
  pod 'ImageViewer.swift/Fetcher'
  pod 'TTTAttributedLabel'
  
  # Pods for ios-swift-pjsua2

end
