-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrMMIzWjXDA1iAg/G
Gifi1Ik/kqQOgPoMkhmpZNCUv8GgCgYIKoZIzj0DAQehRANCAARyeu1mCpi9aKFP
5/W4d7nGVdKjQe4eN6XijukyVkvtVgTy/HnOO6DrLXE4QiFICra0zuxsreXiRVxf
3jzssAH5
-----END PRIVATE KEY-----